snyk/snyk-gradle-plugin

lib/gradle-dep-parser.js
test/fixtures/version-issue/gradle-dependencies-output.txt
test/functional/gradle-dep-parser.test.js

- fixes a subtle parsing error
- run the tests

fix: handle un-versioned version substitution

---

.gitignore

package-lock.json file is transient and should be ignored by git

---

.travis.yml
appveyor.yml
lib/index.js
package.json
test/functional/gradle-plugin.test.js
test/system/plugin.test.js

https://snyksec.atlassian.net/browse/BST-513

fix: run system tests in AppVeyor by preinstalling Gradle

---

lib/index.js
lib/init.gradle
test/system/plugin.test.js

https://github.com/snyk/snyk-gradle-plugin/issues/33

fix: correctly handle scanning of .gradle file for a subproject

---

lib/index.ts
lib/init.gradle
test/functional/gradle-plugin.test.ts

https://snyksec.atlassian.net/browse/BST-530
https://github.com/snyk/snyk/issues/409

fix: disable parallel builds

---

.travis.yml

Snyk CLI does it already
Node 10 is active LTS https://github.com/nodejs/Release/blob/master/README.md

chore: enable Node.js 10 in Travis, to be on par with Snyk CLI

---

lib/index.ts
test/system/plugin.test.ts

Don't fail is a user provided a sub-project name with a space, trim it off.

fix: Trim sub-project names

---

test/fixtures/multi-project-parallel/build.gradle
test/fixtures/multi-project-parallel/gradle.properties
test/fixtures/multi-project-parallel/settings.gradle
test/fixtures/multi-project-parallel/subproj0/build.gradle
test/fixtures/multi-project-parallel/subproj1/build.gradle
test/fixtures/multi-project-parallel/subproj2/build.gradle
test/fixtures/multi-project-parallel/subproj3/build.gradle
test/fixtures/multi-project-parallel/subproj4/build.gradle
test/system/multi-module.test.ts

test: verify parallel builds are supported

---

.travis.yml
package.json
test/common.ts

Reverts snyk/snyk-gradle-plugin#48

Revert "Test/ts node"

---

test/system/multi-module.test.ts
tsconfig.json

Test: different names for different depRoots

---

test/fixtures/multi-project/subproj/build.gradle
test/system/multi-module.test.ts

test: multiDepRoot and configuration flags together

---

.travis.yml
package.json

Updates proces of semanti release.

chore: update npm release step

---

lib/errors/index.ts
lib/errors/missing-sub-project-error.ts
lib/index.ts
test/system/failure-states.test.ts

When specified subproject is not found, error message provides list of available subprojects.
`test/system/failure-states.test.ts`

feat: list all available subproject if subproject is not found

---

lib/errors/missing-sub-project-error.ts
test/system/failure-states.test.ts

test: correct assertion for missing sub-project

---

package.json

Update the strange version for ts

chore: Update strange ts version

---

lib/index.ts
test/functional/gradle-plugin.test.ts

Adds debugging output, e.g. for https://github.com/snyk/snyk/issues/491

fix: more debugging output for error cases

---

lib/index.ts
tslint.json

Removes extra debug output erroneously introduced; added a tslint rule to prevent such mistakes.

fix: remove unnecessary debugging output

---

README.md

Update the README, Node 4 is not a thing anymore.

docs: remove obsolete notice from the README.md

---

lib/index.ts

Prints the Gradle command to assist with debugging even the successful runs of CLI.

fix: print the Gradle command in debug output

---

.gitignore
lib/errors/missing-sub-project-error.ts
lib/index.ts
lib/sub-process.ts
package.json
test/common.ts
test/functional/gradle-plugin.test.ts
test/manual/android.spec.ts
test/system/darwin.test.ts
test/system/failure-states.test.ts
test/system/multi-module.test.ts
test/system/windows.test.ts
tsconfig-test.json
typings/tap/index.d.ts

Uses "legacy" type definitions from https://github.com/snyk/snyk-cli-interface (some fields are renamed, so THIS WOULD ALSO REQUIRE CHANGES IN SNYK CLI).
Included:
* Typescript compilation is not only `strict`, but also `noImplicitAny`
* a "dry-run" tsc compilation of tests before running them
* delicious, home-baked type definitions for Tap
This paves the way for us to:
* better understand the interface between the plugins and the CLI
* improve the code quality of the plugins
* safely migrate to DepGraph without the fear of losing data.
https://github.com/snyk/snyk-cli-interface/blob/master/lib/legacy/plugin.ts
inspect function in index.ts in this repo
(CLI changes needed)
This paves the way for us to:
* better understand the interface between the plugins and the CLI
* improve the code …

BREAKING CHANGE: use the new plugin API, Typescript

---

.travis.yml

Enable testing on java 10 & 11

feat: enable tests on java 10 and 11

---

lib/index.ts
package.json
test/system/multi-module.test.ts

Makes imports more compliant to common Node practices.

chore: use new style imports for CLI interface

---

.travis.yml

Mostly to release previous changes (which were a `chore`)

fix: bump travis Linux image; also, release interface changes

---

test/fixtures/custom-resolution-strategy-via-all/build.gradle
test/fixtures/custom-resolution-strategy-via-asterisk/build.gradle
test/system/plugin.test.ts

Adds tests to cover the cases described in https://github.com/snyk/snyk/issues/729

tests: demonstrate the level of support for custom resolution strategies

---

README.md

Improve docs to clearly state support
Update docs to show supported versions of Java, gradle & node
View here: https://github.com/snyk/snyk-gradle-plugin/blob/a9b330b185d35d81b57ff08dda3dcdcfc3f3299d/README.md

docs: add supported java, gradle, node and os info

---

README.md

Update docs to reflect available gradle CLI options

chore: Update gradle plugin commands docs

---

.travis.yml
lib/index.ts
package.json
test/functional/camelcase.test.ts
test/functional/gradle-plugin.test.ts
test/functional/gradle-version-build-info.test.ts
test/system/multi-module.test.ts

implementation for https://github.com/snyk/snyk-gradle-plugin/issues/89
accidentally closed previous PR (https://github.com/snyk/snyk-gradle-plugin/pull/96) by force pushing with no commits. whooops

feat: store gradle version output meta info

---

lib/index.ts
test/functional/gradle-plugin.test.ts

Disable --no-daemon with --daemon option passed

fix: disable --no-daemon with --daemon option passed

---

package.json

Fixes gradle v2 legacy support (was not generating the legacy task file into the build)

fix: support gradle legacy task

---

lib/index.ts

Fix gradle command version issue

fix: gradle version cmd issue

---

lib/index.ts
lib/init.gradle
package.json
test/system/kotlin.test.ts
test/system/multi-module.test.ts
test/system/plugin.test.ts
tsconfig-test.json
tsconfig.json

- Replace depTree with depGraph
- get correct project version
This PR depends of:
https://github.com/snyk/snyk-cli-interface/pull/34 ✅

feat: support depGraph, drop depTree and get correct project version

---

lib/index.ts

fix: break cycles

---

package.json

Update dep-graph lib that fixes wrong semver version

fix: update dep-graph lib that fixes wrong semver version

---

.travis.yml

chore: fix JDK regex

---

README.md

Link to the snyk for Java docs.

chore: Link to the Snyk for Java documentation

---

lib/index.ts

Add more logging that is useful for debugging issues.

chore: improve debug output

---

lib/find-cycles.ts
lib/index.ts
test/manual/build-graph.spec.ts
test/manual/expected-build-graph.json
test/manual/expected-snyk-graph.json
test/system/kotlin.test.ts
test/system/plugin.test.ts

fix: break edge case cycles

---

.circleci/config.yml

Fix release issue, due to missing dependency
Unfortunately, this commit should be `fix`, cos another way around it won't trigger `semantic release`.

fix: release issue, due to missing dependency

---

package.json

Upgrades cli-interface and dep-graph packages to latest upstream versions.
HAMMER-99

fix: update cli-interface and dep-graph to latest

---

package.json

Upgrades call graph builder dependency to v1.15.1

feat: upgrade call graph builder to 1.15.1

---

package.json

Do not display logs while downloading the call graph generator
https://snyksec.atlassian.net/browse/FLOW-437

feat: do not display logs while downloading the call graph generator

---

lib/find-cycles.ts
test/system/kotlin.test.ts
test/system/plugin.test.ts

fix: enhance cycles detection

---

lib/init.gradle
test/system/failure-states.test.ts
test/system/kotlin.test.ts
test/system/multi-module.test.ts
test/system/plugin.test.ts

This pr handle each resolvable configuration separately as these will be the containers under which Gradle will resolve it's dependencies. We are no longer merging all the configs and attributes. We are giving priority to configs that can be resolved

fix: gradle deps conflict resolution

---

.circleci/config.yml
lib/index.ts
test/fixtures-with-wrappers/with-lock-file/dep-graph.json
test/system/multi-module.test.ts

- Upgrade Circle CI window machine version
- Ensure appropriate JDK version is used when running tests 
- Upgrade test

feat: Update CI Window Machine

---

lib/init.gradle

add resolvedConfiguration log where the work is happening so there is a timestamp between configuration resolving

chore: add resolvedConfiguration log
