lib/index.js

We've had bug reports that indicate that in certain circumstances
"--build-file build.gradle" is being treated by gradle/gradlew as a
single argument (including the space).
I've been unable to replicate the problem, but this change should
ensure that "--build-file" and the target-file path are always treated
as distinct arguments (rather than relying on a space!)

fix: pass arguments separately to spawn

---

lib/index.js
test/functional/gradle-plugin.test.js

Double-dash arguments are now sent as an array of strings, split by spaces.
Supports older, string-string arguments as well, so no breaking change here.

feat: supporting args as an array

---

lib/index.js
lib/sub-process.js
test/system/plugin.test.js

When `gradle` execution ends with an error, the plugin used to reject with a string containing the stdout or stderr of the `gradle` process. This doesn't work well with the CLI, which expects proper `Error` objects on plugin failure. Now fixed!

fix: throw proper error on failing gradle execution

---

lib/gradle-dep-parser.js
test/fixtures/no-wrapper/gradle-dependencies-results.json
test/functional/gradle-dep-parser.test.js

- drops `groupId` and `artifactId` from response
- they are not used (as far as I can tell) and can be determined by looking at `name`
- dep trees can get huge, so this can have quite an impact on the size of the tree (~ 25% smaller from some rough tests).

BREAKING CHANGE: drop unused groupId and artifactId attributes from response

---

lib/index.js

- drops the top-level `from` attribute from the response (so that we know to annotate it later)

fix: drop top-level from path

---

lib/gradle-dep-parser.js
test/fixtures/api-configuration/build.gradle
test/fixtures/api-configuration/gradle-dependencies-output.txt
test/fixtures/api-configuration/gradle-dependencies-results.json
test/functional/gradle-dep-parser.test.js

- strips `(n)` markers when parsing `gradle dependencies` output

fix: handle (n) markers in `gradle dependencies` output

---

lib/index.js
test/fixtures/multi-project/settings.gradle
test/fixtures/multi-project/subproj/build.gradle
test/system/plugin.test.js

to support "multi-project" gradle projects: https://docs.gradle.org/current/userguide/multi_project_builds.html, a new `options['gradle-sub-project']` option allows the caller to specify the desired sub-project to scan.
can `npm link` with the `github.com/snyk/snyk` CLI, go to the `./test/fixtures/multi-proj` folder and run:
```bash
snyk test
snyk test --gradle-sub-project=subproj
```
do we like the naming of this option?

feat: option to specify sub-project in multi-project build

---

lib/index.js

this commit expands on the work done in 66de57e6f0a85e9bb461c1848984608419340560 to handle more cases by using single quotes instead of double, and only if whitespaces are present in the target file, as I believe to be the standard in POSIX.

fix: support target file paths with spaces

---

lib/gradle-dep-parser.js
package.json
test/fixtures/no wrapper/gradle-dependencies-output.txt
test/functional/gradle-dep-parser.test.js
test/functional/gradle-jar-parser.test.js
test/functional/gradle-plugin.test.js
test/system/plugin.test.js

trims off the trailing "(c)" that gradle dependencies command outputs in some cases, leading to missing out vulns.
run test/monitor a gradle project that contains (c) in one of it's dependency resolution. specially if it's a dependency with issues.
it will result on missing vulns on those dependencies. as we don't recognise the right package name.

fix:trimming off trailing (c) - resolution state

---

lib/index.js

Add `targetFile` to `inspect` output for build.gradle.kts files support.
https://github.com/snyk/snyk/pull/395
https://snyksec.atlassian.net/browse/BST-398

fix: add targetFile to inspect output for build.gradle.kts files support

---

lib/index.js

Don't send targetFile for Groovy gradle projects as it is used to construct project name and will create a new project for existing users

feat: Only send targetFile for kotlin to avoid breaking overrides & changing existing project names

---

README.md
lib/index.ts
lib/sub-process.ts
package.json
test/functional/gradle-plugin.test.ts
test/system/plugin.test.ts
tsconfig.json
tslint.json

Converts the project to Typescript.
Most of the tslint rules disabled for now to keep the diff minimal.
No type definitions added yet.
We are working on modernizing Gradle support. To make sense of the logic we could use some type definitions.
Motivated by https://snyksec.atlassian.net/browse/BST-508

refactor: convert to Typescript (no proper lint, no types yet)

---

.travis.yml
lib/index.ts
test/functional/gradle-plugin.test.ts

Gradle is hard. Let's run our tests against several different Gradle versions to minimize a possibility of introducing a regression.

test: run tests against multiple Gradle versions

---

appveyor.yml

We've dropping Node.4 support for Snyk CLI.

chore: switch AppVeyor build to test against Node.js 10 instead of 4

---

.travis.yml
lib/index.ts
package.json
test/common.ts
tsconfig.json

- node-tap has added typescript/ts-node support, so let's use it
- removing `test` from tsconfig `include` has change the output folder structure
- ~make sure Windows tests run~ They do!

chore: switch back to non-forked node-tap

---

lib/index.ts
lib/init.gradle
test/manual/README.md

* when specifying a concrete configuration, preserve its attributes
* if failing due to unmergeable configurations, display actionable suggestions for the user
index.ts and the message there; init.gradle; test/fixtures/android-cannot-auto-resolve/app/build.gradle 
run snyk test on various Gradle projects (android and not)
Should be all in the error message and comments.
If anything is not clear - let's add the comments.
https://snyksec.atlassian.net/browse/BST-528

fix: work around non-mergeable configs in Android builds

---

lib/index.ts
test/system/multi-module.test.ts

When doing a simple (one sub-project) scan, return the names of all subprojects, so that the CLI can advertise trying all-sub-project scans.
https://snyksec.atlassian.net/browse/BST-540

feat: for single-deproot scans, return also the names of all subprojects

---

lib/init.gradle
test/fixtures/multi-project-dependency-cycle/build.gradle
test/fixtures/multi-project-dependency-cycle/settings.gradle
test/fixtures/multi-project-dependency-cycle/subproj/build.gradle
test/system/multi-module.test.ts

Fix for StackOverflowError when scanning projects with dependency cycles.
Terminate the recursive function when encountering a cycle. 
init.gradle
See the added fixture.
https://snyksec.atlassian.net/browse/BST-575

fix: handle circular dependencies in Gradle scans

---

lib/index.ts
lib/init.gradle
test/fixtures/api-configuration/build.gradle
test/fixtures/multi-project-some-unscannable/settings.gradle
test/fixtures/multi-project-some-unscannable/subproj-fail/build.gradle
test/fixtures/multi-project-some-unscannable/subproj/build.gradle
test/system/multi-module.test.ts

Before, init.gradle script always scanned all subprojects. This means if one of the subprojects fails for some reason, all of them do.
Now, if it only needs to scan one project, it will scan one.

fix: make the injected script scan only one sub-project

---

lib/index.ts
lib/init.gradle
test/system/multi-module.test.ts

The feature to advertise all-sub-projects was de-facto disabled by https://github.com/snyk/snyk-gradle-plugin/pull/67; this change restores the check by returning the list of the projects explicitly.

fix: reinstate advertising all-sub-projects when only scanning one

---

lib/index.ts
lib/init.gradle
lib/sub-process.ts
package.json

Enables realtime logging from within the `init.gradle` script.
Output lines prefixed by "ECHO " will be output as debug messages by the Snyk CLI.
init.gradle, especially comments at the top
`DEBUG=snyk-gradle-plugin snyk test` on a Gradle project.
Many of our customers experience Gradle analysis as pretty slow. We should investigate how the time is being spent.

feat: add debugging output to the injected script

---

lib/index.ts

Needed to enable logging in the plugin using the "-d" flag in the Snyk CLI.

fix: lazy initialization for the logger, to play nice with Snyk CLI

---

lib/init.gradle

Before, snyk processed only the "current" project and its children. Now we will process all.
Apart from the obvious convenience, it also helps with resolving the projects via `--configuration-attributes` flag: if a project depends on its sibling project, we need to check the attributes of the sibling projects to correctly build the set of attributes that reliably matches dependency variants.
Also, apply the config name filter when building the attribute set. Should not affect most use cases, but is a logical thing to do.

fix: scan all sub-projects even when not starting from the root

---

lib/index.ts

The support was broken due to a subtle regex bug :(
This is just a fix; a separate PR with tests will also be added.

fix: support for legacy `-- --configuration=foo` CLI option

---

lib/index.ts
lib/init.gradle
test/fixtures/multi-config-attributes-subproject/build.gradle
test/fixtures/multi-config-attributes-subproject/settings.gradle
test/fixtures/multi-config-attributes-subproject/subproj/build.gradle
test/system/plugin.test.ts

To make sure the constructed configuration is compatible with all the sub-projects of the project, we should scan all of them to find attributes that match user specification.
We even have a comment explaining why we should have been doing that, but we were only scanning a specified project. This has caused problems for some our customers.
Drive-by: recognise one more variant of Gradle error message related to unresolvable variants when displaying extended error message.

fix: scan all subprojects when selecting attributes for conifguration

---

.github/CODEOWNERS

Add Boost as code owners so we can enable this feature to require a review from someone from the team

chore: Add boost as code owners

---

lib/index.ts
package.json

Updates the plugin Typescript interface (version bump for snyk/cli-interface).
v1.3.1 is the one we want; v1.4.0 didn't work out after all and will be reverted via https://github.com/snyk/snyk-cli-interface/pull/10
Also, some code formatting and comment updates.

fix: expose all three inspect() overloads in plugin types

---

README.md
lib/index.ts
package.json
test/system/kotlin.test.ts
test/system/multi-module.test.ts
test/system/plugin.test.ts

What does this PR do?
Fixes #93 . Problem was the project name was not being picked correctly.

feat: get correct project name

---

.travis.yml

JDK8 is not being installed before being used.
Also, since SDKMAN will change versions and removing old ones, it make sense to make the installation of the version a bit more generic

fix: fix gradle for jdk8

---

package.json

Remove `clone-deep` cos it's not used since https://github.com/snyk/snyk-gradle-plugin/commit/04cf66ddfa4cd484e609836ee5f10f2ae95daefb

fix: remove unused dep that was bringing vulns

---

.travis.yml

Updating to Node 10 is desirable by `semantic release` and Node 8 was stopping plugin from being 
released
https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md

fix: semantic release

---

.travis.yml
lib/index.ts
test/functional/gradle-plugin.test.ts

This PR forces `plain` console mode when executing Gradle commands. If it's not set, then build output contains control ANSI characters and generated JSON cannot be parsed.
This PR was triggered by failed issues in teamcity plugin.
Compare 2 Travis builds:
- failed build after console mode is manually set from outside: https://travis-ci.org/snyk/snyk-gradle-plugin/builds/633516869
- passed build after console mode is set for each Gradle command executing https://travis-ci.org/snyk/snyk-gradle-plugin/builds/633540774

fix: plain console mode

---

lib/index.ts
lib/legacy-init.gradle
package.json
test/system/multi-module.test.ts
test/system/plugin.test.ts

This PR, brings the initial support of graphs to this snyk-cli plugin.
At the moment with the change of data structure from Tree to Graph on the gradle task, we are avoiding OOM on java heap while executing it to load a huge amount of projects, but while we do not change snyk-cli contract rules to allow it of receives Acyclic depGraphs from plugins, we are converting processed graphs back to depTree out of the gradle task. Once the contract rules of cli changes, the  convertDepGraphToDepTree method will be deleted.
I would like to point out that at the moment only Gradle v3+ will be using the initial new graph support, we kept for now v2 with the previously gradle task that we had and it's now considered as legacy.
With gradual steps, tests will be rewritten more concise with Jest and …

fix: gradle oom issue

---

lib/index.ts
package.json

Send back targetFile as meta so we can still use the information for messaging and other purposes without sending it to the backend where it is not expected for `build.gradle`
This allows a feature that compares detected vs scanned gradle projects to help identify issues or orphaned build files.
https://github.com/snyk/snyk/pull/1355/files

feat: send back sub-project targetFile

---

lib/gradle-attributes-pretty.ts
lib/index.ts
test/functional/gradle-plugin.test.ts

Extract all the attributes on error & for `-d` mode which helps with Android scans to narrow down the buildType + flavour to scan. The attributes help construct the correct `--attributes-matching` parameter

feat: always print attributes on error with -d

---

package.json

Updates to the new snyk-config version that should get shipped with the CLI first.
Requirement for snyk/snyk#1524
Follow up to the snyk/config#43 and https://github.com/snyk/java-call-graph-builder/pull/37

fix: update java-call-graph-builder

---

lib/index.ts
package.json
test/system/plugin.test.ts

We want to make sure that the right gradle util is being used within the java call graph builder to allow gradle
sub projects to use the correct gradlew, which can be found in the root of the project.
For more context go to
https://github.com/snyk/java-call-graph-builder/pull/42
https://snyksec.atlassian.net/browse/FLOW-564

feat: pass gradle util to java call graph builder

---

lib/graph.ts
test/fixtures-with-wrappers/basic-with-deps/dep-graph-gradleNormalizeDeps-failed-search.json
test/functional/graph.spec.ts

Discovered a bug in the graph builder when using a coordinate map.
The id used to query the snykGraph needs to be the original id, not the id from the coordinate map.
We should have noticed in the test that chops off the transitive line abruptly. Now test/fixtures-with-wrappers/basic-with-deps/dep-graph-gradleNormalizeDeps-failed-search.json includes the full graph, even when resolution fails.

fix: transitives when using gradle-normalize-deps

---

.circleci/config.yml
.gitignore
lib/graph.ts
lib/index.ts
package.json
test/fixtures-with-wrappers/basic-with-deps/dep-graph-gradleNormalizeDeps-failed-search.json
test/fixtures-with-wrappers/basic-with-deps/dep-graph.json
test/fixtures-with-wrappers/basic-with-failed-dep/dep-graph.json
test/fixtures-with-wrappers/configuration-consistency/dep-graph.json
test/fixtures-with-wrappers/custom-configuration/dep-graph.json
test/fixtures-with-wrappers/empty-build-gradle-in-root/dep-graph.json
test/fixtures-with-wrappers/empty-project/dep-graph.json
test/fixtures-with-wrappers/kts-basic-with-deps/dep-graph.json
test/fixtures-with-wrappers/kts-configuration-consistency/dep-graph.json
test/fixtures-with-wrappers/kts-strict-lock-mode/dep-graph.json
test/fixtures-with-wrappers/kts-version-catalog-module/dep-graph.json
test/fixtures-with-wrappers/platform-project-mvn-bom/dep-graph.json
test/fixtures-with-wrappers/repo-content-filtering/dep-graph.json
test/fixtures-with-wrappers/version-catalog-settings/dep-graph.json
test/fixtures-with-wrappers/version-catalog-toml/dep-graph.json
test/fixtures-with-wrappers/with-lock-file/dep-graph.json
test/fixtures/pruned-spring-app/dep-graph.json
test/manual/gradle-stdout.spec.ts
test/system/fixtures-with-wrappers.test.ts
test/system/kotlin.test.ts
test/system/multi-module.test.ts
test/system/plugin.test.ts

There is a discrepancy between what we call our projects and what we call our root nodes in the dependency graphs. This sounds like it should not matter, but it does.
We have a regression introduced after a bugfix was made last month, where `snyk test` now does not correctly pick up ignores in the ui after a `snyk monitor` on certain types of Gradle projects.
Doing this change will fix that.
(Links to internal projects)
* [This](https://github.com/snyk/registry/blob/ac4373282fbc6d6a145cc9bf4fab2518e0d7b144/src/web/routes/api/v1/monitor.ts#L165-L168) is how we make a project id in `monitor`.
* [This](https://github.com/snyk/registry/blob/d078339f187dfe5b9de4789e03fa823e54bac81f/src/web/routes/api/v1/test/dep-graph.ts#L125-L130) is how we make a project id in `test`.
Since the bugfix last …

feat: [SUP-2164] Change dependency graph root name logic

---

.circleci/config.yml
.github/workflows/pr-housekeeping.yml
.releaserc.json

Each of the the pipeline executors spent like 4-6 minutes downloading the same things on each run.
* Added the usual `pr-housekeeping` Github workflow for stale branches and PRs
* Added cache steps for all downloads
* Removed old and obsolete Node version steps and added new LTS
* Replaced homemade Node installations with the CircleCI orb
* Default branch to `main`
* Added missing `requires`

Pipeline cleanup

---

lib/init.gradle

FIxes concurrency issue brought by new versions of org.springframework.boot
`* What went wrong:
Execution failed for task ':snykResolvedDepsJson'.
> java.util.ConcurrentModificationException (no error message)
---`

Fix: solved concurrency issue when looping a map

---

lib/init.gradle
test/fixtures-with-wrappers/with-lock-file/dep-graph.json
test/system/multi-module.test.ts

This comes in completion of [this PR raise by the client](https://github.com/snyk/snyk-gradle-plugin/pull/268), adding tests
What this does
This resolves https://github.com/snyk/snyk-gradle-plugin/issues/195, allowing the tool to properly recognize --sub-project arguments that refer to nested subprojects, e.g. foo/bar for the Gradle project path :foo:bar.

Fix: subprojects filtering

---

.circleci/config.yml
lib/index.ts
lib/sub-process.ts
test/system/failure-states.test.ts

This change will resolve an issue that occurs when Gradle is not available on the user's machine, which causes an error to be thrown.
_Instructions on how to run this locally, background context, what to review, questions…_
_Visuals that may help the reviewer_

feat: handle spawn error on gradle command

---

lib/index.ts
lib/init.gradle
test/fixtures/modern-android/app/build.gradle
test/fixtures/modern-android/build.gradle
test/fixtures/modern-android/settings.gradle
test/functional/gradle-plugin.spec.ts
test/system/android.test.ts
test/system/kotlin.test.ts

Relatively inelegantly handles https://github.com/snyk/snyk-gradle-plugin/issues/306.
More specifically, the main issue encountered in `v5.0.0` for Android projects was failures to correctly resolve certain module artifacts as some configurations presented criteria that no module could meet. A simple `try/catch` here results in `v5.0.0` producing effectively identical dep-graphs as were produced by `v4.9.2` -- however, the solution seems a little inelegant to me, and I would prefer one that could check ahead of time whether some configuration would fail on the call to `getModuleArtifacts()`.
This _does not_:
* Uncover why moving to resolved artifacts over resolved dependencies was problematic for android
* Address the probably faulty "one artifact per dependency" assumption
Also included …

fix: Safely handle module artifact retrieval failures
